### PR TITLE
Pass -non-interactive by default

### PR DESCRIPTION
**Pull request by longwa**
Prevents stopping build for prompts

### CODE REVIEW

**Comment by ConnorWGarvey** [comment]
Sorry, I haven't been ignoring this.  I tried to make the build run mostly as it would in the regular Grails build, including prompts.  I agree that there shouldn't be interactive prompts in the build at all, but in Grails there are.  I can't decide whether this should be a switch.  There are some commands like "create-app" that definitely _should_ be interactive, so this could also be a per-command configuration.

**Comment by longwa** [comment]
No worries. I see that Grails 2.1.0 has a new "wrapper" command which essentially bootstraps a grails environment. I may check that out and see how it works. I still like having the ability to use gradle to handle build tasks, though.

**Comment by ljohnston** [comment]
This is a showstopper for our use of this plugin.

**Comment by ConnorWGarvey** [comment]
@ljohnston, it's possible to pass it as an argument just as you would for the `grails` command.  This helps in automated environments.  I'll double check when I have access to a project, but I'm pretty sure it's `gradle grails-command -Parg0=--non-interactive`.

This plugin was deprecated the day it was created because the Grails project is planning to use Gradle in version 3, so I don't plan to spend a lot more time on it.  If there's a version of this pull request that doesn't break any commands, I'd be happy to merge it.

**Comment by kdorff** [comment]
Has there been any work toward this? I'll be committing my gradle/grails project to our Jenkins server any day now and when it upgrades plugin versions and such it prompts and this will make it hard to use against Jenkins which won't give me the ability to hit "yes" on a keyboard.

I agree that for things like create app, that yes, there are things that should be interactive but a create-war shouldn't be interactive or at least I should be able to specify a property so that things aren't interactive. If I update to a newer plugin, when it builds on the server I would want it to always respond "yes".

**Comment by longwa** [comment]
This is long dead and I wanted it off my PR list, closing.

**Pull request closed without merging**
